name: vnpt_his
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.1.4
  table_calendar: ^3.0.9
  flutter_bloc: ^9.0.0
  sqflite: ^2.2.8+4
  path_provider: ^2.1.1
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.17
  icon_font_generator: ^4.0.0
  shared_preferences: ^2.5.2
  http: ^1.3.0
  webview_flutter: ^4.4.2
  url_launcher: ^6.1.11
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.4.0
  lottie: ^3.3.1
  equatable: ^2.0.7
  internet_connection_checker: ^1.0.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.3
  flutter_card_swiper: ^7.0.2
  flutter_localization: ^0.3.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  flutter_inappwebview: ^6.1.5
  go_router: ^14.8.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  bloc: ^9.0.0
  flutter_pdfview: ^1.4.0
  permission_handler: ^11.3.1
  fl_chart: ^0.70.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/app_icon.png" # Đặt icon tại đây
  adaptive_icon_background: "#ffffff" # (Tùy chọn) Background cho Android adaptive icon
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/ket_qua_kham.pdf
    - assets/languages/en.json
    - assets/languages/vi.json
    - assets/images/common/
    - assets/images/home/
    - assets/images/login/
    - assets/images/landing/
    - assets/images/product/
    - assets/images/profile/
    - assets/images/icon/
    - assets/anim/
    - assets/images/navigation/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf